import { type NextPage } from "next";
import Head from "next/head";
import { useState, useEffect } from "react";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const allProducts = trpc.example.getAll.useQuery();
  const [navbar, setNavbar] = useState(false);

  return (
    <>
      <Head>
        <title>PreisDetektiv</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className="font-mono text-xl">
      <nav className="w-full bg-black shadow border-b-2">
        <div className="mx-auto justify-between md:flex md:items-center md:px-8 lg:max-w-7xl">
          <div>
            <div className="flex items-center justify-between py-3 md:block md:py-5">
              <a href="javascript:void(0)">
                <h2 className="text-5xl font-bold text-white">PreisDetektiv</h2>
              </a>
              <div className="md:hidden">
                <button
                  className="rounded-md p-2 text-gray-700 outline-none focus:border focus:border-gray-400"
                  onClick={() => setNavbar(!navbar)}
                >
                  {navbar ? (
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-6 w-6 text-white"
                      viewBox="0 0 20 20"
                      fill="currentColor"
                    >
                      <path
                        fillRule="evenodd"
                        d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                        clipRule="evenodd"
                      />
                    </svg>
                  ) : (
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-6 w-6 text-white"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                      strokeWidth={2}
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M4 6h16M4 12h16M4 18h16"
                      />
                    </svg>
                  )}
                </button>
              </div>
            </div>
          </div>
          <div>
            <div
              className={`mt-8 flex-1 justify-self-center pb-3 md:mt-0 md:block md:pb-0 ${
                navbar ? "block" : "hidden"
              }`}
            >
              <ul className="items-baseline justify-center space-y-8 md:flex md:space-x-6 md:space-y-0">
                <li className="text-white hover:text-indigo-200">
                  <a href="javascript:void(0)">Startseite</a>
                </li>
                <li className="text-white hover:text-indigo-200">
                  <a href="javascript:void(0)">Kategorien</a>
                </li>
                <li className="text-white hover:text-indigo-200">
                  <a href="javascript:void(0)">Ueber uns</a>
                </li>
                <li className="text-white hover:text-indigo-200">
                  <a href="javascript:void(0)">Hilfe</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </nav>
      <main className="grid min-h-screen grid-cols-1 items-start bg-black text-white text-lg">
        <div>
          <div className="m-5">
            {allProducts.data?.map((item?) => (
              <div className="grid grid-cols-3 rounded-md border p-4 mb-6" key={item.articleId}>
                <div className="flex justify-center">{item?.product_name}</div>
                <div className="flex justify-center">{item?.priceHistory[0]?.price[0]?.branchName}</div>
                <div className="flex justify-center">{item?.priceHistory[0]?.price[0]?.price ? `${item?.priceHistory[0]?.price[0]?.price} Euro` : ""}</div>
              </div>
            ))}
          </div>
        </div>
      </main>
      </body>
    </>
  );
};

export default Home;
